config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :tickets do
    resources :comments
  end
  resources :tags, except: :show

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :creator, class_name: "User"
  belongs_to :ticket

  validates :body, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  has_many :tickets, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :taggings, dependent: :destroy

  scope :with_counts, -> {
    left_outer_joins(:taggings).select("tags.*, COUNT(taggings.id)").
      group("tags.id")
  }

  scope :alphabetical, -> { order("tags.name ASC") }
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :ticket
  belongs_to :tag
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  STATUSES = %w(new blocked in_progress fixed)

  validates :name, presence: true
  validates :status, inclusion: { in: STATUSES }
  validates :project_id, presence: true

  belongs_to :project
  belongs_to :creator, class_name: "User"
  belongs_to :assignee, class_name: "User", optional: true
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, dependent: :destroy

  scope :open, -> { where("status != ?", "fixed") }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, format: /.+@.+/, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= user_for_session(session[:user_id])
  end
  helper_method :current_user

  def require_session
    unless current_user
      redirect_back alert: "You must be logged in to do that.",
        fallback_location: root_path
    end
  end

  def user_for_session(user_id)
    User.find(user_id) if user_id
  end

  def sign_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_session
  before_action :set_ticket
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :require_creator, only: [:edit, :update, :destory]

  def edit; end

  def create
    @comment = @ticket.comments.new(comment_params.merge(creator: current_user))

    if @comment.save
      if params[:ticket_status].present?
        @ticket.update_attribute(:status, params[:ticket_status])
      end
      redirect_to @ticket, notice: 'Comment was successfully created.'
    else
      render :edit
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @ticket, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to @ticket, notice: 'Comment was successfully destroyed.'
  end

  private

  def set_comment
    @comment = @ticket.comments.find(params[:id])
  end

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def require_creator
    if current_user != @comment.creator
      redirect_to @ticket, alert: "You can only edit your own comments."
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :require_session, except: [:show, :index]

  def index
    @projects = Project.all
  end

  def show; end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      sign_in(@user)
      redirect_to root_path, notice: "Welcome back!"
    else
      redirect_to login_path, notice: "You could not be logged in."
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :require_session, except: [:show, :index]

  def index
    @tags = Tag.with_counts.alphabetical
  end

  def new
    @tag = Tag.new
  end

  def edit; end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to tags_path, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path, notice: 'Tag was successfully destroyed.'
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destory]
  before_action :require_session, except: [:show, :index]

  def index
    @tickets = Ticket.all
  end

  def show; end

  def new
    @ticket = Ticket.new
  end

  def edit; end

  def create
    @ticket = Ticket.new(ticket_params.merge(creator: current_user))

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully created.'
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Ticket was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :body, :status, :project_id, :assignee_id, tag_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: 'Welcome to the ticketing system'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def tag_list(ticket)
    if ticket.tags.any?
      ticket.tags.map(&:name).join(', ')
    else
      "-"
    end
  end
end

app/views/comments/_form.html.erb
<%= form_for [@ticket, comment] do |form| %>

  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body, "Add a comment" %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="field">
    <%= label_tag :ticket_status, "Update ticket status" %>
    <%= select_tag :ticket_status, options_for_select(Ticket::STATUSES.map{|t| [t.titleize, t]}, params[:ticket_status]), id: :ticket_status, include_blank: "Do not change" %>
  </div>

  <div class="actions">
    <%= form.submit %>
    or
    <%= link_to "Cancel", ticket_path(@ticket) %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>
  <% @comment.new_record? ? "Creating" : "Editing" %>
  Comment
</h1>

<%= render 'form', comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="container">
      <nav class="main-nav">
        <ul class="left">
          <li><strong>Ticketing</strong></li>
          <li><%= link_to "Projects", projects_path %></li>
          <li><%= link_to "Tickets", tickets_path %></li>
          <li><%= link_to "Tags", tags_path %></li>
        </ul>

        <ul class="right">
          <li>
            <% if current_user %>
              Signed in as <%= current_user.name %> <%= link_to "Logout", '/logout' %>
            <% else %>
              <%= link_to 'Login', '/login' %> or <%= link_to 'Signup', '/signup' %>
            <% end %>
          </li>
        </ul>
      </nav>

      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>

      <%= yield %>
    </section>

    
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to "Show", project_path %> |
<%= link_to "Back", projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% if @projects.empty? %>
  <p class="empty-list">There are no projects</p>
  <%= link_to "Add a project?", new_project_path %>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th class="number">Open Tickets</th>
        <th class="number">Total Tickets</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td class="number"><%= project.tickets.open.count %></td>
        <td class="number"><%= project.tickets.count %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<br />
<%= link_to "New Project", new_project_path, class: "btn" %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p><%= @project.description %></p>

<%= link_to "Edit", edit_project_path %>
<%= link_to "Delete", @project, method: :delete, data: { confirm: 'Are you sure?' } %>

<h1>Tickets</h1>


<% if @project.tickets.empty? %>
  <p>There are no tickets!</p>
<% else %>
  <%= render 'tickets/list', tickets: @project.tickets %>
<% end %>

app/views/tags/_form.html.erb
<%= form_for(tag) do |form| %>

  <% if tag.errors.any? %>
    <div>
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name, id: :tag_name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<% if @tags.empty? %>
  <p class="empty-list">There are no tags!</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th class="number">Tickets</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td class="number"><%= link_to tag.taggings.count, tickets_path(tag: tag) %></td>
          <td>
            <%= link_to "Edit", edit_tag_path(tag) %>
            or
            <%= link_to "Destroy", tag, method: :delete, data: { confirm: "Are you sure?"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br />

<%= link_to "New Tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tickets/_form.html.erb
<%= form_for(ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project %>
    <%= form.collection_select :project_id, Project.all, :id, :name, id: :ticket_project_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ticket_name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :ticket_body %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Ticket::STATUSES.map{|t| [t, t]}, id: :ticket_status %>
  </div>

  <div class="field">
    <%= form.label :assignee, "Assigned To" %>
    <%= form.collection_select :assignee_id, User.all, :id, :name, id: :ticket_assignee_id, include_blank: "No one" %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.collection_select :tag_ids, Tag.alphabetical, :id, :name, {}, multiple: true,  id: :ticket_tag_ids, size: Tag.count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/tickets/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Assignee</th>
      <th>Status</th>
      <th>Tags</th>
      <th></th>
    </tr>
  </thead>
  <tbody>


    <% tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.name, ticket_path(ticket) %></td>
        <td><%= ticket.assignee.try(:name) %></td>
        <td><%= ticket.status %></td>
        <td><%= tag_list(ticket) %></td>
        <td>
          <%= link_to "Edit", edit_ticket_path(ticket) %>
          <%= link_to "Delete", @ticket, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>


  </tbody>
</table>

app/views/tickets/edit.html.erb
<h1>Edit Ticket</h1>

<%= render 'form', ticket: @ticket %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<div class="ticket-filters">
  <%= form_tag tickets_path, method: :get, enforce_utf8: false do %>
    <p>
      Show tickets from
      <%= select_tag :project, options_from_collection_for_select(Project.all, :id, :name, params[:project]), include_blank: "All Projects" %>
      with status
      <%= select_tag :status, options_for_select(Ticket::STATUSES.map{|t| [t.titleize, t]}, params[:status]), include_blank: "Any Status" %>
      tagged
      <%= select_tag :tag, options_from_collection_for_select(Tag.alphabetical, :id, :name, params[:tag]), include_blank: "-" %>

      <%= button_tag "Update", name: nil %>
      <span><%= link_to "Clear Filters", tickets_path %></span>
    </p>
  <% end %>
</div>

<% if @tickets.empty? %>
  <p class="empty-list">There are no tickets!</p>
<% else %>
  <%= render 'list', tickets: @tickets %>
<% end %>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

app/views/tickets/show.html.erb
<h1><%= @ticket.name %></h1>
<p><%= @ticket.body %></p>

<p><%= tag_list(@ticket) %></p>

<p class="actions">
  <%= link_to "Edit", edit_ticket_path(@ticket) %>
</p>


<br />

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Creator</th>
      <th>Assignee</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @ticket.status.titleize %></td>
      <td><%= @ticket.creator.name %></td>
      <td><%= @ticket.assignee ? @ticket.assignee.name : '-' %></td>
    </tr>
  </tbody>
</table>

<h2>Comments</h2>

<% if @ticket.comments.any? %>
  <% @ticket.comments.each do |comment| %>
    <div class="comment">
      <p><%= comment.body %></p>
      <p>
        <em>
          posted by
          <%= comment.creator.name %>
          <%= time_ago_in_words(comment.created_at) %> ago
          <% if comment.created_at != comment.updated_at %>
            - updated <%= time_ago_in_words(comment.updated_at) %> ago
          <% end %>
        </em>
      </p>
      <p><%= link_to "Edit", edit_ticket_comment_path(@ticket, comment) %></p>
    </div>
  <% end %>
<% else %>
  <p>There are no comments.</p>
<% end %>

<%= render "comments/form", comment: Comment.new %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, url: signup_path) do |f| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being created:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, id: :user_email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, id: :user_password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Create Account" %>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>